name = "dinostore"
version = "1.0.0"
target = "javascript"
description = "Gleam bindings to the Deno.Kv database"
licences = ["Apache-2.0"]
repository = { type = "github", user = "MystPi", repo = "dinostore" }

[javascript]
runtime = "deno"
typescript_declarations = true

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_javascript = ">= 0.12.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
